#!/bin/bash
# ----------------------------------------------------------------------------
# @file package_color
# Create a color package for distribution
# @author Alister Lewis-Bowen [alister@different.com]
# ----------------------------------------------------------------------------

VERSION=${1:-latest};
PACKAGE_NAME=color_${VERSION};
FILES='color README LICENSE';

if [ -e color ]; then
	tar -cvf ${PACKAGE_NAME}.tar $FILES;
	gzip ${PACKAGE_NAME}.tar ;
	zip ${PACKAGE_NAME}.zip $FILES;
else
	echo "I'm not able to find the color script. Please run this in the directory containing the color script.";
fi;
